### ISSUE TITLE
Traverse Nested Dicts

### ISSUE THREAD

**Issue by stongo** [modcloth-labs/ansible-module-etcd#4]
It would be _amazing_ to be able to supply this module with a nested dict, and then have it walk the dict.
This would allow passing a nested dict from group_vars and saving them in etcd on a host.
Example:

```
foo:
  bar: "hello"
  char:
     moo: "cow"
```

would write the following keys

```
/bar 'hello'
/char/moo 'cow'
```
